export const  GET_PRODUCTS = 'GET_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_BASKET = 'DELETE_FROM_BASKET';
export const DECREASE_FROM_CART = 'DECREASE_FROM_CART';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const DELETE_FROM_WISHLIST = 'DELETE_FROM_WISHLIST';

